### ISSUE TITLE
Bad typo for CONTENT_TYPE in Leaf\Http\Request getContentType()

### ISSUE THREAD

**Issue by yannux** [leafsphp/http#17]
Hi, 

In `Request::getContentType()`  https://github.com/leafsphp/http/blob/cc03c75373a80987a00529df561c6ace47d9615c/src/Request.php#L361C9-L361C9

Header key is CONTENT_TYPE , but the good header name is with a  dash **-**  not an underscore **_**   : `Content-Type`

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type

![image](https://github.com/leafsphp/http/assets/533125/ca4bed49-766f-4435-ae05-e4f73fe53765)

**Comment by mychidarko** [comment]
Thanks for catching this @yannux . It has been fixed and will be available in the next release.
