### ISSUE TITLE
PUT Request Body Form Data

### ISSUE THREAD

**Issue by rittjom** [leafsphp/http#2]
Hi,

currently when you using request()->params("xy") and your content was passed via PUT Request (form-data), theres no chance to get the data. 
I know php is missing something like $_PUT / $_PATCH. But you can get the data via php://input. Like you do for json content.
(see Request.php line 189 -> and line 50)

Current Workaround is to use POST or to use json body in my request.
I think laravel has the same "problem". So you can see this as a feature request :)

**Comment by mychidarko** [comment]
Hi @rittjom, actually, using `request()->params("xy")` still grabs PUT request data. This is taken care of when the request package is initialized.

![image](https://user-images.githubusercontent.com/26604242/168441528-0aead9c5-b8c2-4be9-bede-a1d5dfb306d6.png)

**Comment by rittjom** [comment]
static::$request is only used when json_decode successfully returned an array.
I don't have a json content in my example. content type is x-www-form-urlencoded.
![grafik](https://user-images.githubusercontent.com/13555220/168441694-d008d9ea-5f52-4eaa-ba74-1749532be393.png)
otherwise only $_GET,$_FILES,$_POST are merged for using as key value params.

Maybe I'm still missing something?

**Comment by mychidarko** [comment]
Ohhh I get your point. You're not missing anything. 👍🏽

**Comment by rittjom** [comment]
If you want to adapt the code, you could perhaps put also the json_decode into a variable, instead of using it twice. Only as a small performance boost :)
Otherwise I wanted to say that leaf is a really nice and simple rest framework. Thank you for all the effort you put into it. Greetings from Germany ❤️

**Comment by mychidarko** [comment]
Yeah noticed those smaller issues. Old code 😂
I'm currently rewriting all that stuff so this input is very much appreciated, and thanks for the support as well.
Love from Ghana 🇬🇭

**Comment by mychidarko** [comment]
Completely fixed now - https://github.com/leafsphp/http/commit/aead66a4f874e5de30bd59718700ac052e0eb987
