### ISSUE TITLE
request()->postData() not working for JSON requests

### ISSUE THREAD

**Issue by patrickvuarnoz** [leafsphp/http#25]
The `postData()` method only looks at `$_POST` which does not cover the data from a JSON request body:

````
public static function postData($item = null, $default = null)
{
    return \Leaf\Anchor::deepGet($_POST, $item) ?? $default;
}
````

Interestingly the `get()` method does. And `rawData()` also. This might be confusing for someone not sending form data to the server as it is not intuitive.

**Comment by mychidarko** [comment]
`get()` allows you to retrieve any information found in the request no matter where it's coming from, whether it's from $_POST, $_GET or raw data.

The other methods were added to give you control over the source of the data. The only use-case for those other methods are if you have data coming from multiple inputs which have the same key. I get that it's quite confusing, but the hope is for them to not be used in the first place.
