### ISSUE TITLE
Support a response->raw() method

### ISSUE THREAD

**Issue by patrickvuarnoz** [leafsphp/http#29]
None of the response methods allow to completely freely compose a response. In my case I wanted to create file response but with `Content-Disposition: inline` which is not supported by the framework. My suggestion would be to add a `raw()` method that just outputs what is passed to it. Something along these lines:

````
    /**
     * Output raw data
     *
     * @param mixed $data The data to output
     * @param int $code The response status code
     */
    public function plain($data, int $code = 200)
    {
        $this->status = $code;
        $this->content = $data;

        $this->send();
    }

````

Like that there is way to do whatever you want with full support of the framework. For example:

````

response()
        ->withHeader('Content-Type: application/pdf')
        ->withHeader('Content-Length: ' . strlen($rawData))
        ->withHeader('Content-Disposition: inline; filename="' . $filename . '"')
        ->raw($rawData)
````

**Comment by patrickvuarnoz** [comment]
Just realized that there is the `echo()`method which does exactly what I was looking for. Would be good if that was documented.

**Comment by mychidarko** [comment]
This has also been added, will be deployed soon. Thanks
