### ISSUE TITLE
A newly installed Leaf v3 will output a 1 at the last character after running

### ISSUE THREAD

**Issue by Jarvie789** [leafsphp/http#6]
<img width="506" alt="2022-09-06 13 48 16" src="https://user-images.githubusercontent.com/27297429/188556538-22f3cdf6-f014-47e9-b7bd-bc1024c5a30c.png">

**Comment by mychidarko** [comment]
Hi @Jarvie127. I'll check it out

**Comment by mychidarko** [comment]
This has been fixed now, a new released will be pushed in a bit

**Comment by Jarvie789** [comment]
> This has been fixed now, a new released will be pushed in a bit

thanks, bro

**Comment by mychidarko** [comment]
This issue is fixed by https://github.com/leafsphp/http/releases/tag/v2.1.0
